### ISSUE TITLE
Using comment variable on fmgr_firewall_address

### ISSUE THREAD

**Issue by CyrielRct** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#11]
Hello,
I'm trying to specify the comment on firewall_address object. According to the exemple the comment field seems to be a string 
`firewall_address:
           allow-routing: disable
           associated-interface: any
          #  cache-ttl: <value of integer>
          #  color: <value of integer>
          #  comment: <value of string>`

source : https://github.com/fortinet-ansible-dev/fortimanager-playbook-example/blob/2.0.0/src/fmgr_firewall_address.yml

But when I'm specifying the comment string I'm getting the following error who tells me to use dictionary object instead of string : 

> "msg": "argument comment is of type <type 'str'> found in 'firewall_address'. and we were unable to convert to dict: dictionary requested, could not parse JSON or key=value"

it doesn't make any sens for me that comment is based on dict object !? but if it's the case what's the structure of it ? 
Thank you

**Comment by chillancezen** [comment]
hi @CyrielRct , thank you so much for using FortiManager collection.

we've fixed this issue, and will be available in next patch very soon. 

meanwhile, you can still use `string` in your playbook by setting `bypass_validation` to `True`.

we will keep you updated once new patch release is ready, please let us know if you have any issues.

thanks again.
Link

**Comment by CyrielRct** [comment]
Thank you for your quick answer :) 
Nice cat btw ;)

**Comment by chillancezen** [comment]
please see fix in release `2.0.1`
https://galaxy.ansible.com/fortinet/fortimanager
https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/galaxy-2.0.1/index.html
