### ISSUE TITLE
dvm_cmd_add_device: reports os_ver 6.0 invalid

### ISSUE THREAD

**Issue by mnantel** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#12]
fatal: [fmg]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "bypass_validation": false,
            "dvm_cmd_add_device": {
                "adom": "ciussstest",
                "device": {
                    "adm_usr": "admin",
                    "mgmt_mode": "fmgfaz",
                    "mr": 4,
                    "os_type": "fos",
                    "os_ver": "6",
                    "platform_str": "FortiGate-VM64",
                    "sn": "FGVM04TM00000001"
                },
                "flags": [
                    "create_task",
                    "nonblocking"
                ],
                "groups": null
            },
            "rc_failed": null,
            "rc_succeeded": null,
            "workspace_locking_adom": null,
            "workspace_locking_timeout": 300
        }
    },
    "msg": "value of os_ver must be one of: unknown, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, got: 6 found in dvm_cmd_add_device -> device"
}

**Comment by chillancezen** [comment]
this fix will be included in next patch release 2.0.1.

thanks,
Link

**Comment by chillancezen** [comment]
to preview the fix, use:
https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/releases/download/preview-2.0.1/fortinet-fortimanager-2.0.1.tar.gz
https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/galaxy-2.0.1/index.html

**Comment by chillancezen** [comment]
please see fix in release `2.0.1`
https://galaxy.ansible.com/fortinet/fortimanager
https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/galaxy-2.0.1/index.html
