### ISSUE TITLE
fmgr_pkg_firewall_policy not taking in lists

### ISSUE THREAD

**Issue by rrobles12** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#17]
For the fmgr_pkg_firewall_policy the following parameters aren't taking lists anymore:

srcintf        
dstintf        
srcaddr        
dstaddr        
service

Example:
```
        dstaddr: 
          - H-1-1-1-1
          - H-1-1-1-2
```

Returns:
`fatal: [site_pkg]: FAILED! => {"changed": false, "meta": {"request_url": "/pm/config/adom/DEV/pkg/site_pkg/firewall/policy", "response_code": -10131, "response_data": {"policyid": 7201}, "response_message": "datasrc invalid. object: Policy package \"\" - firewall policy.7201:dstaddr. detail:  [\\'H-1-1-1-1\', \\'H-1-1-1-2\\']. solution: datasrc invalid"}, "rc": -10131}
`
Feeding it directly as a list returns the same which I was doing prior in 1.0.3 without issues:

Example:
`
        dstaddr: ['H-1-1-1-1', 'H-1-1-1-1-2']
`
Do I need to do  something different? Also getting these warnings, which I didn't get before:

`The value "['H-1-1-1-1', 'H-1-1-1-2']" (type list) was converted to ""['H-1-1-1-1', 'H-1-1-1-2']"" (type
string). If this does not look like what you expect, quote the entire value to ensure it does not change`

ansible --version
ansible 2.10.5

```
ansible-galaxy collection list
Collection            Version
--------------------- -------
ansible.netcommon     1.2.1
fortinet.fortimanager 2.0.1
```

**Comment by chillancezen** [comment]
hi @rrobles12 ,

here is the quick workaround to run your playbook with multiple values.:
```
...
bypass_validation: true
...
```

the exported API spec define them as single string., though it actually accepts a list.
<img width="1716" alt="1611833587328" src="https://user-images.githubusercontent.com/10312789/106152519-7e8d5380-61b8-11eb-9f84-e65523cb6120.png">

thanks,
Link

**Comment by rrobles12** [comment]
This worked. Thanks!
