### ISSUE TITLE
Some of the module short descriptions have funny formatting

### ISSUE THREAD

**Issue by samccann** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#25]
The formatting on modules such as the following:
https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/blob/galaxy/2.0.3/plugins/modules/fmgr_dvmdb_workspace_unlock_obj.py#L27

Does not render properly either in docs.ansible.com or Automation Hub. 
![image](https://user-images.githubusercontent.com/30267855/120374667-d6170980-c2e7-11eb-940c-eb56622cde9f.png)

**Comment by chillancezen** [comment]
@samccann , could you help let us know when it is expected to be fixed?

**Comment by samccann** [comment]
Someone here needs to remove the <i> xxx </i> as it is not part of a valid short description. Use text only.

**Comment by chillancezen** [comment]
fixed with newly published collections! thanks
