### ISSUE TITLE
Support for check_mode

### ISSUE THREAD

**Issue by WebSpider** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#47]
A quick search shows that check_mode is currenty not supported:

```
$ grep supports_check_mode fortinet/fortimanager/plugins/modules/fmgr_* | grep -v False
$
```
Could support for this please be added, as this would save a lot of work figuring out if changes are needed using for instance the fact modules?

**Comment by lix-fortinet** [comment]
Hi @WebSpider,

Thank you for raising this issue. We will discuss and consider it, and will get back to you once we implement it.

Thanks,
Xing

**Comment by cr0cdev** [comment]
Hi!

Do we have any updates regarding this?

**Comment by dux-fortinet** [comment]
Hi @cr0cdev,

Thanks for pointing it out. I'm working on it.
If everything goes well, "check_mode" will be supported in the next release before September.

Thanks,
Dux

**Comment by cr0cdev** [comment]
Hi @dux-fortinet 

Will it support full diff as well?

**Comment by dux-fortinet** [comment]
Hi @cr0cdev,

The development of "check_mode" and bug fix for GitHub issue 87 have been completed and are currently undergoing QA verification.  It will be released before September.
I am working on the "diff" mode now. It has many edge cases. I'm not sure whether "diff" can be supported in the next release timely. If not, "diff" will be supported in two versions later.

Thanks,
Dux

**Comment by dux-fortinet** [comment]
FortiManager Ansible 2.7.0 has been released, and "check mode" has been supported in this version.
The "diff" mode has many special cases and requires thorough QA validation. It will be supported in 2.8.0.
For discussion regarding diff mode, please go to [Github issue 88](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/issues/88)
