### ISSUE TITLE
Collection Requirements Violation - Repository Management

### ISSUE THREAD

**Issue by gotmax23** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#53]
Hi! The Ansible Community Steering Committee has determined that this collection does not tag its releases in its git repository. This violates the [repository management](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#repository-management) section of the Collection Requirements:

> Every collection MUST have a public git repository. Releases of the collection MUST be tagged in said repository. This means that releases MUST be `git tag`ed and that the tag name MUST exactly match the Galaxy version number. Tag names MAY have a `v` prefix, but a collection's tag names MUST have a consistent format from release to release.
>
> Additionally, collection artifacts released to Galaxy MUST be built from the sources that are tagged in the collection's git repository as that release. Any changes made during the build process MUST be clearly documented so the collection artifact can be reproduced.

Note that this requirement has recently [been clarified](https://github.com/ansible-collections/overview/commit/6dbb5037c09dce9324cb39e322be2f42e068f117), but its intent remains the same. Please tag at least the previous 1-2 releases of your collection to come into compliance. I understand that this collection currently stores each release in a separate branch, but that does not meet this requirement.

Please keep us updated and let us know if you have any questions. Thanks!

**Comment by lix-fortinet** [comment]
Hi @gotmax23,

Thank you for your notification. We will update it.

Thanks,
Xing

**Comment by gotmax23** [comment]
Great! Please also `git tag` the last two releases of this collection.

**Comment by lix-fortinet** [comment]
Sure, no problem.

Thanks,
Xing

**Comment by gotmax23** [comment]
@lix-fortinet, has there been any progress here? It looks like this was fixed for fortinet.fortios but not for this collection.

**Comment by chillancezen** [comment]
@gotmax23 thanks Max, I will be doing this today.~

**Comment by gotmax23** [comment]
It looks like 2.1.7 has been tagged as https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/releases/tag/2.1.7. Thank you for fixing this!
