### ISSUE TITLE
Machine-readable changelog removed from collection release

### ISSUE THREAD

**Issue by felixfontein** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#67]
I noticed that the latest 2.2.1 release no longer contains `changelogs/changelog.yaml`, which is used by Ansible to compile the combined changelog (https://github.com/ansible-community/ansible-build-data/blob/main/8/CHANGELOG-v8.rst).

It was removed from the collection artefact in https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/commit/1913d2b0de2e4829077d96f91ea062e584d40394#diff-1ade2795a7b410581d689fb0faa358b769c2d189b2d549e8f530b706f09b2fb7R72.

Please adjust or undo this change so that `changelogs/changelog.yaml` is again included in the collection release. Thanks.

**Comment by dux-fortinet** [comment]
Thanks for raising this issue. We will contain `changelogs/changelog.yaml` in the next release. Thanks.

**Comment by dux-fortinet** [comment]
`changelogs/changelog.yaml` has been added in FortiManager Ansible Collection 2.3.0
Thanks for pointing it out.
