### ISSUE TITLE
fmgr_pkg_firewall_policy error when update existing policy

### ISSUE THREAD

**Issue by williamnie2088** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#7]
hi there,

i have experienced with multiple error when using method: "update" on an existing policy even set "loose_validation: False" or "loose_validation: True".

i also noticed when building new policy, it only will work with "loose_validation: True" and "method: set".

script i used that works:
  tasks:
    - name: create policy in the object
      fmgr_pkg_firewall_policy:
        method: 'set'
        loose_validation: true
        url_params:
            adom: something
            pkg: something
        params:
          - data:
            - name: 'test' 
              action: 'accept'
              srcintf: 
                - something
              dstintf: 
                - something
              srcaddr: 
                - something
                - something
              dstaddr: 
                - something
                - something
              service: 'something'
              schedule: 'always'
              av-profile: 'something'
              webfilter-profile: "something"
              ips-sensor: "something"
              application-list: "something"
              utm-status: 1
              profile-type: 0
      register: output

The script i used with loose_validation: False and dont work:
#- name: REQUESTING /PM/CONFIG/PKG/{PKG}/FIREWALL/POLICY
    #  fmgr_pkg_firewall_policy:
    #    loose_validation: False
    #    method: set
    #    url_params:
    #      adom: something
    #      pkg: something
    #    params:
    #      - data:
    #        - name: test
    #          comments: something
    #          action: accept
    #          scrint: something
    #          dstinf: something
    #          srcaddr:
    #            - something
    #            - something
    #          dstaddr:
    #            - something
    #            - something
    #          schedule: always
    #          status: enable 
    #          service: something
    #          policyid: 20
    #          app-av-profile: "something"
    #          webfilter-profile: "something"
    #          ips-sensor: "something"
    #          application-list: "something"
    #          utm-status: 1
    #          profile-type: 0
    #  regsiter: output

can you please advise if i'm missing something? 
thanks

**Comment by chillancezen** [comment]
hi @williamnie2088 , 

https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/latest/example.html hosts many runnable examples which have minimal parameters. could you search `fmgr_pkg_firewall_policy ` in the searching box?


note these examples are for FMG collection later than v2.0.0, if you insist on using legacy collection,  you can easily select and tune corresponding parameters. 

please let us know if you have any questions.

thanks,
link.

**Comment by chillancezen** [comment]
https://raw.githubusercontent.com/fortinet-ansible-dev/fortimanager-playbook-example/2.0.0/output/fmgr_pkg_firewall_policy.yml(
https://github.com/fortinet-ansible-dev/fortimanager-playbook-example/blob/2.0.0/output/fmgr_pkg_firewall_policy.yml )

value for each parameter must be correct to avoid error (-11, invalid data source)

**Comment by chillancezen** [comment]
closing. feel free to reopen if the issue persists.
