### ISSUE TITLE
We (the ansible steering commitee) see some problems with this collection

### ISSUE THREAD

**Issue by mariolenz** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#77]
We (the ansible steering commitee) see some problems with this collection. One thing is the sheer size of the collection. But we see some other problems, too.

At the moment, we are discussing if we should remove this collection from the community package. It would be great if you could join the [discussion](https://forum.ansible.com/t/should-we-keep-the-fortinet-collections-fortinet-fortimanager-fortinet-fortios-in-the-community-ansible-package).

After all, we might be wrong :shrug:

**Comment by lix-fortinet** [comment]
Hi @mariolenz,

Thank you for letting us know. We will join the discussion and improve our collection to fix these problems.

Happy New Year!

Thanks,
Xing

**Comment by dux-fortinet** [comment]
The FortiManager Ansible 2.4.0 reduces the size to 21MB now. Thanks for raising this issue.
