### ISSUE TITLE
Community package requirements: sanity tests

### ISSUE THREAD

**Issue by gotmax23** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#80]
# Community package requirements: sanity tests

(Note: This issue was filed in a semi-automated fashion. Let me know if you see errors in this issue.)

As per the [Ansible community package inclusion requirements][ci-testing], collections must pass `ansible-test sanity` tests. Version `2.3.0` of `fortinet.fortimanager`, corresponding to the `2.3.0` tag in this repo, fails one or more of the required sanity tests.

Please see the errors below and address them. If these issues aren't addressed within a reasonable time period, the collection may be subject to [removal from Ansible][removal].

Thank you for your efforts and for being part of the Ansible package! We appreciate it.

---

## Sanity tests

The following tests were run using `ansible-test` version `2.16.1`:

- ansible-doc
- compile
- validate-modules
- yamllint

Note that this is only a subset of the required sanity tests. Please make sure you run them in all in your CI.

### Results

The test `ansible-test sanity --test validate-modules` [[explain](https://docs.ansible.com/ansible-core/2.16/dev_guide/testing/sanity/validate-modules.html)] failed with 13015 errors:

**Issue truncated. [Click here to read more](https://gist.github.com/gotmax23/45113b9789d6e185bce08de86c8d9aac).**

[ci-testing]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#ci-testing
[repo-mgmt]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#repository-management
[removal]: https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst

**Comment by dux-fortinet** [comment]
Thanks for raising this issue.
FortiManager Ansible 2.3.0 has sanity-test ignore files that ignore the parameter-invalid problems. However, its ignore files support ansible 2.9 ~ 2.15, and the test environment in this post is 2.16, which leads to the errors.

Meanwhile, All sanity test problems will be solved in 2.4.0, which is expected to be released within 2 weeks. Thanks.

**Comment by dux-fortinet** [comment]
We just released fortimanager ansible 2.4.0
Sanity test problems should be fixed in this version.
Thanks for raising this issue.
