### ISSUE TITLE
Add filter support for fmgr_fact fmg_variable_dynamicmapping param.

### ISSUE THREAD

**Issue by cr0cdev** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#89]
Hi!

Could you also add "filter" support for fmgr_fact module fmg_variable_dynamicmapping param. When looking at the API documentation I can see that filter should be supported. Would it be possible to add it?

Thanks!

**Comment by dux-fortinet** [comment]
Hi @cr0cdev ,

Currently FortiManager Ansible `fmgr_fact` module already supports `filter`.
I can use the following script to get results correctly with the "filter" specified:

```
- name: Github89
  hosts: fortimanagers
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: Get fact
      fortinet.fortimanager.fmgr_fact:
        facts:
          filter: ["value", "==", "string"]
          selector: "fmg_variable_dynamicmapping"
          params:
            adom: "root"
            variable: test
            # dynamic_mapping: "FGVMMLTM00000000/root" # Optional parameter, "<your deive name>/<your device vodm>"
      register: response
    - name: Display response
      debug:
        var: response
```

Please feel free to let me know if you have any questions.

Best,
Dux
