### ISSUE TITLE
Issue with fmgr_system_admin_user

### ISSUE THREAD

**Issue by mnantel** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#9]
Following task results in an error that cannot easily be understood:

    fmgr_system_admin_user:
      bypass_validation: False
      state: present
      system_admin_user:
        change-password: enable
        force-password-change: disable
        password: fortinet
        policy-package:
        - policy-package-name: all_policy_packages
        profileid: Super_User
        rpc-permit: none
        restrict-dev-vdom: 
        two-factor-auth: disable
        user_type: local
        userid: testuser
        wildcard: disable

Error:

    "meta": {
        "request_url": "/cli/global/system/admin/user",
        "response_code": -10,
        "response_data": [],
        "response_message": "The data is invalid for selected url"
    },

I have queried directly via API and converted an existing user's JSON to YAML and attempted to deploy that without any more success than the above.

**Comment by chillancezen** [comment]
thank you Mathieu @mnantel for the issue, 

please set `bypass_validation: False` to `bypass_validation: True` in your playbook to work it around. 
the root cause is: default values of the modules are not recognized. 

we will fix it in v2.0.1

thanks,
Link

**Comment by chillancezen** [comment]
please see fix in release `2.0.1`
https://galaxy.ansible.com/fortinet/fortimanager
https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/galaxy-2.0.1/index.html
