### ISSUE TITLE
Assign Template Group and not CLI template Group

### ISSUE THREAD

**Issue by arnaudpenc44** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#94]
Hello,

I need to assign a device to a template Group (tmplgrp). 

I found a way to do it for a **cli** template group but not for template Group (tmplgrp) - fmgr_templategroup.py - but this one is for **cli** template group.

Can you help me please?

Thank you

**Comment by dux-fortinet** [comment]
Hi @arnaudpenc44,

Based on my testing, the backend JSON API for Template Group is `/pm/tmplgrp/adom/{adom_name}` and `/pm/tmplgrp/adom/{adom_name}/{tmplgrp_name}`.

However, those APIs are not listed on the [FNDN](https://fndn.fortinet.net/index.php?/fortiapi/5-fortimanager/), which means those APIs are used for internal only and may be various in different FMG versions. Therefore, the `tmplgrp` related APIs are not yet supported by the FMG Ansible.

Currently, you can use the module `fortinet.fortimanager.fmgr_generic` to send custom requests to the FortiManager.
The following scripts work well in my testing environment (FMG 7.6.0)


![github94_fig1](https://github.com/user-attachments/assets/11d59794-a726-4cd0-bf06-5ebaad0ce5af)

[READ] You can use this script to get details of one existing template group:
```
- name: Github94
  hosts: fortimanagers
  connection: httpapi
  vars:
    adom_name: "root"
    tmplgrp_name: "test"
  tasks:
    - name: Get existing template groups
      fortinet.fortimanager.fmgr_generic:
        method: "get"
        params:
          - url: "/pm/tmplgrp/adom/{{adom_name}}/{{tmplgrp_name}}"
      register: response
    - name: Display response
      debug:
        var: response
```

[UPDATE] You can use this script to assign one or more devices to an existing template Group:
```
- name: Github94
  hosts: fortimanagers
  connection: httpapi
  vars:
    adom_name: "ansible74"
    tmplgrp_name: "test"
  tasks:
    - name: Assign one or more devices to an existing template Group
      fortinet.fortimanager.fmgr_generic:
        method: "set"
        params:
          - url: "/pm/tmplgrp/adom/{{adom_name}}/{{tmplgrp_name}}"
            data:
              scope member: # List of devices
                - name: "DEVICE NAME 1"
                  vdom: "root"
                # - name: "DEVICE NAME 2"
                #   vdom: "DEVICE VDOM"
                # - name: "DEVICE NAME 3"
                #   vdom: "DEVICE VDOM"
      register: response
    - name: Display response
      debug:
        var: response
```

[CREATE] You can use this script to create a new template group
```
- name: Github94
  hosts: fortimanagers
  connection: httpapi
  vars:
    adom_name: "ansible74"
    tmplgrp_name: "test_create"
  tasks:
    - name: Get existing template groups
      fortinet.fortimanager.fmgr_generic:
        method: "add"
        params:
          - url: "/pm/tmplgrp/adom/{{adom_name}}"
            data:
              - name: "{{tmplgrp_name}}"
                template group setting:
                  description: "exampe description"
                  # Provisioning Templates
                  cliprofs: []
                  wtpprofs: ["11ac-only", "FAP221E-default", "AP-11N-default"]
                  fspprofs: []
                  fxtprofs: []
                  templates: ["1__default", "4-1__BRANCH_IPsec_Recommended"]
                type: "tmplgrp"
                scope member: # List of devices
                  - name: "DEVICE NAME 1"
                    vdom: "root"
                  # - name: "DEVICE NAME 2"
                  #   vdom: "DEVICE VDOM"
                  # - name: "DEVICE NAME 3"
                  #   vdom: "DEVICE VDOM"
      register: response
    - name: Display response
      debug:
        var: response
```

For the proper values of `wtpprofs`, `templates` in `params->data-> template group setting` in this [CREATE] script, you can create a template group in the GUI, and use [READ] script to read the details of that template group.

Please let us know if you have any further questions regarding the template group.


Best,
Dux

**Comment by arnaudpenc44** [comment]
Hello,
Thank you for your fast reply, it works. 
I hope the tmplgrp related APIs will be supported by the FMG Ansible :).

**Comment by dux-fortinet** [comment]
You are welcome.
The tmplgrp related APIs are not on the FNDN yet, which means those APIs are either for internal use or they are not mature.
FMG Ansible will support tmplgrp as soon as the related APIs are listed on the FNDN :)
